### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by flik** [gma/nesta#162]
getting this error: You don't have permission to access / on this server. 

I have given full permissions

**Comment by gma** [comment]
This isn't a Nesta bug, but is related to the configuration of the web server that you're trying to run it with. If you'd like some help with it, please post a message to the Nesta mailing list and let us know which web server you're using, what you typed in order to start it up, how you've configured Nesta to work with the web server, and which operating system you're using.

Cheers…
