### ISSUE TITLE
License

### ISSUE THREAD

**Issue by shark-oxi** [gma/nesta#168]
Hello,

may be if you want to be more part of the open source community and see Nesta added to a static generator website list like [Staticgen](https://www.staticgen.com/) you'll have to change your copyright license to a open source license.

Tell me what you think about it.

Best regrds.

**Comment by gma** [comment]
Hi. Nesta isn't actually a static site generator. It's licensed under the MIT license (about as "open source" as you can get).

https://github.com/gma/nesta/commit/1c4db11ae87c09006c8561bb2db776acabab4fb9

Cheers.

**Comment by shark-oxi** [comment]
Hi,

oh I'm sorry i didn't recognize the MIT license.
Nesta is a CMS but it read into markdown and textile files to provide html content ? So isn't it also a static site generator ?
Can you explain me the difference please ?

Thanks

**Comment by gma** [comment]
Sure. A "static site" is a web site made up entirely of pre-generated HTML files. So you update your HTML files when you update the site.

Nesta doesn't do that; it generates the HTML on the fly, as a page is requested. There are pros and cons of both approaches.

- Static sites can be hosted on any server that can serve an HTML file. Nesta needs Ruby to be installed on the server.
- Static sites cannot (by definition) contain code containing a security hole to give people access to your server. Nesta doesn't actually contain any code that people could exploit to gain access to the server, but it's technically feasible that a bug might be found in Nesta (or Sinatra, on which Nesta is built). This isn't likely, so I wouldn't let this influence your decision.
- Static sites are very inflexible – all they can do is serve HTML and assets (e.g. images, CSS, JavaScript). That means you can't add forms to your web site that (when submitted) cause data to be submitted to the server, stored in a database, etc. Nesta is a lightweight CMS built from a lightweight web framework. That means that anything you can build on the web, you can build on top of Nesta (i.e. your site can do anything).
- Nesta is also built using very similar tools used in frameworks like Ruby on Rails, which means you can embed Nesta in your Rails app.

The fact that Nesta gets its content from a text file, rather than from a database server, doesn't mean it's "static". It just means you need a different "user interface" to update your "database" – I use a text editor and git, but you could use your iPad and a Dropbox client.

Basically, if you change the Markdown or Textile file, Nesta will serve new HTML immediately.

Nesta is more flexible, static site generators have fewer dependencies.

**Comment by shark-oxi** [comment]
Hum, a great thanks for your explanation, I thought Nesta did that but that text files was genereted to static HTML the first time nad not on the fly. So that's all my bad.

Have a great evening.
