### ISSUE TITLE
Question: ERB support

### ISSUE THREAD

**Issue by olimart** [gma/nesta#196]
Hello and thanks for sharing Nesta.
Just wondering what it would take to support ERB templates?

Thanks.

**Comment by gma** [comment]
Hi. They're supported — have you seen these docs?

https://nestacms.com/docs/design/templating-engines

I'm planning on making ERB the default before long, just because more people will be familiar, and the whole file-based CMS thing has kind of blown up since I made Haml the default!

Let me know if you've got more questions...

**Comment by gma** [comment]
Also, check the version 0.14.0 release blog post if you'd like to use it as a static site generator. I've not had time to write the full docs for that yet (SSG is a new feature), but the bits you need are all mentioned in that post.

**Comment by olimart** [comment]
Great. 

I read https://nestacms.com/docs/creating-content/
> Enter some text (formatted as Markdown, Textile or Haml).

Thank you.

**Comment by gma** [comment]
> > Enter some text (formatted as Markdown, Textile or Haml).

Ah yes, the docs talk about "templates" and "content" separately, which perhaps isn't that obvious when you're just getting setup for the first time. And that mention of Haml is a bit misleading too. It's accurate though; you can't create an ERB page inside `./content/pages`, ERB is currently only supported for templates in `./views`.
